# 這是根據你的要求，剔除最後一部分單字後的「精確版」單字庫
if "words" not in st.session_state:
    st.session_state.words = [
        # --- 第一張照片內容 ---
        {"en": "Ambivert", "zh": "中性性格者 (50% 50%)"},
        {"en": "Rational", "zh": "理性的"},
        {"en": "Delusional", "zh": "幻想的/妄想的"},
        {"en": "Complexion", "zh": "膚色/面色"},
        {"en": "Disciplined", "zh": "紀律的/自律的"},
        {"en": "Character", "zh": "特點/性格"},
        {"en": "Ludicrous", "zh": "可笑的/荒唐的"},
        {"en": "Rigid", "zh": "死板的/堅硬的"},
        {"en": "Versatile", "zh": "多才多藝的"},
        {"en": "Zodiac", "zh": "十二生肖/黃道帶"},
        {"en": "Nurture", "zh": "培育/養育"},
        {"en": "Offend", "zh": "得罪/冒犯"},
        {"en": "Put up with", "zh": "忍受"},
        {"en": "To pay the price", "zh": "付出代價"},
        {"en": "Bragging", "zh": "吹牛/自誇"},
        {"en": "Obnoxious", "zh": "令人討厭的"},
        {"en": "Profanity", "zh": "髒話/褻瀆"},
        {"en": "Irk", "zh": "使厭煩/惱火"},
        {"en": "Predict", "zh": "預測"},
        {"en": "Obligation", "zh": "義務/責任"},
        {"en": "Conduct", "zh": "執行/行為"},
        {"en": "Masculine", "zh": "男性的/陽剛的"},
        
        # --- 第二張照片內容 ---
        {"en": "Panoramic", "zh": "全景的/全景畫"},
        {"en": "Financial commitment", "zh": "財務承諾"},
        {"en": "Enthusiast", "zh": "愛好者/熱衷者"},
        {"en": "Trial", "zh": "審判/試驗"},
        {"en": "Backpacking", "zh": "自助旅行/背包旅行"},
        {"en": "Devour", "zh": "吞食/狼吞虎嚥"},
        {"en": "Braised", "zh": "燉的/滷的"},
        {"en": "Consumption", "zh": "消耗/消費"},
        {"en": "Determine", "zh": "決定/確定"},
        {"en": "Involve", "zh": "涉及/包含"},
        {"en": "Compulsory", "zh": "強制的/義務的"},
        {"en": "Particular", "zh": "挑剔的/獨特的"},
        {"en": "Monetary relief", "zh": "貨幣救助/資金援助"},
        {"en": "Superstition", "zh": "迷信"},
        {"en": "Merchant", "zh": "商人"},
        {"en": "Unworthy", "zh": "不值得的"},
        {"en": "Netherworld", "zh": "冥界/地府"},
        {"en": "Prevalent", "zh": "流行的/普遍的"},
        {"en": "Mandatory", "zh": "強制的/指令的"},
        {"en": "Bride", "zh": "新娘"},
        {"en": "Despite", "zh": "儘管/雖然"},
        {"en": "Ruling", "zh": "裁決/判決"},
        {"en": "Cremation", "zh": "火葬"},
        {"en": "Urging", "zh": "催促/力勸"},
        {"en": "Ancestors", "zh": "祖先"}
    ]
